import { NavBar } from "@/components/common/navbar/NavBar";


export const metadata = {
  title: "Music Management | Home",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <div className="h-screen main-background relative">
      <NavBar />
      {children}
    </div>
  );
}
